### ISSUE TITLE
Conflicting classes

### ISSUE THREAD

**Issue by jenschr** [myflashlab/GPS-ANE#15]
We use quite a few of the ANE's from Milkman and apparently they're in conflict with some of the common ANE definitions that you use. Any suggestion as to how I solve this?

Here's the compiler error from Flash Builder:

```
Error occurred while packaging the application:
dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/common/api/Api$ApiOptions$HasOptions;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
	at com.android.dx.command.dexer.Main.run(Main.java:247)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/android/gms/ads/identifier/AdvertisingIdClient;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:737)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
	at com.android.dx.command.dexer.Main.run(Main.java:247)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
2 errors; aborting
```

**Comment by myflashlab** [comment]
This is a popular problem and it's neither their fault not ours. What you can try is to see if their dependencies are as up-to-dated as ours? we are currently using Google Play Services 9.0.1 and Android Support 23.4.0

If they match, you can safely remove one of the dependencies and compile your project (we have no idea how they have developed their dependencies so, this might not work. This is just a case)

Anyway, one of the main reason that we introduced the [MyFlashLab ANE club](http://www.myflashlabs.com/product/myflashlabs-club-membership/) has been to help Air developers use all the ANEs they would require from one source to avoid such conflicting problems. And we are trying to add all the ANEs that Air developers would require.

I hope you would find this message helpful but I have to close the ticket because it's not related to any specific issue/problem with the GPS ANE directly. For more talks on this regard though, please contact us through http://www.myflashlabs.com/contact/

**Comment by jenschr** [comment]
ok, but could you at least tell me which one of your ANE files that contain the two mentioned classes?

**Comment by myflashlab** [comment]
I'm not sure how that might help but i will look into this and update you
a.s.a.p

On Wednesday, June 15, 2016, Jens Chr Brynildsen <notifications@github.com>
wrote:

> ok, but could you at least tell me which one of your ANE files that
> contain the two mentioned classes?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/myflashlab/GPS-ANE/issues/15#issuecomment-226191173>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABnVFJn1dqHaRlDLVRAEZ7m5y-_BKQK6ks5qMAHEgaJpZM4I2VQF>
> .
>


-- 
Sent from iPhone

**Comment by jenschr** [comment]
Looks like AdvertisingIdClient is in basement.ane and the other error is related to base.ane. If I exclude both, I won't get compile-time errors, but getting the location fails (gracefully).

**Comment by myflashlab** [comment]
@jenschr We have changed the licensing on our ```Common Dependency ANEs``` so it allows all other ANE developers to use our dependency ANEs for free so hopefully the conflicting problem between different ANE providers will be fixed once and forever.

**Comment by myflashlab** [comment]
you can learn more about this change here: http://www.myflashlabs.com/air-native-extension-conflict/

**Comment by jenschr** [comment]
@myflashlab goodie! I'm now using your ANE with the Milkman extensions and it works fine!

**Comment by myflashlab** [comment]
As a side not, you should just make sure the dependency ANE you are using is the same version as required by the target extension. because if they don't match, it's probable that the target ANE is calling a method on the dependency ANE and if it can't find it, your app will shut down!
